export const projects = [
  {
    id: "PJ001",
    year: "2025",
    title: "Webiste Rekomendasi Smartphone",
    tecnology: "HTML, CSS, Javascript",
    image: ["display1.png", "display2.png", "display3.png"],
    desc: "Sebuah website yang menyediakan layanan rekomendasi hp berdasarkan kriteria yang dimasuka pengguna.",
    linkRep: "https://github.com/dimaswidysap/rekomendasihp",
    linkDemo: "https://dimaswidysap.github.io/rekomendasihp/",
  },
  {
    id: "PJ002",
    year: "2025",
    title: "Webiste Rekomendasi Smartphone 1",
    tecnology: "HTML, CSS, Javascript",
    image: "rekomendasihp.png",
    desc: "Sebuah website yang menyediakan layanan rekomendasi hp berdasarkan kriteria yang dimasuka pengguna.",
    linkRep: "https://github.com/dimaswidysap/rekomendasihp",
    linkDemo: "https://dimaswidysap.github.io/rekomendasihp/",
  },
  {
    id: "PJ003",
    year: "2025",
    title: "Webiste Rekomendasi Smartphone 2",
    tecnology: "HTML, CSS, Javascript",
    image: "rekomendasihp.png",
    desc: "Sebuah website yang menyediakan layanan rekomendasi hp berdasarkan kriteria yang dimasuka pengguna.",
    linkRep: "https://github.com/dimaswidysap/rekomendasihp",
    linkDemo: "https://dimaswidysap.github.io/rekomendasihp/",
  },
  {
    id: "PJ004",
    year: "2025",
    title: "Webiste Rekomendasi Smartphone 3",
    tecnology: "HTML, CSS, Javascript",
    image: "rekomendasihp.png",
    desc: "Sebuah website yang menyediakan layanan rekomendasi hp berdasarkan kriteria yang dimasuka pengguna.",
    linkRep: "https://github.com/dimaswidysap/rekomendasihp",
    linkDemo: "https://dimaswidysap.github.io/rekomendasihp/",
  },
];
