export const projects = [
  {
    id: "PJ001",
    year: "2025",
    title: "GetPhone",
    page: "",
    reasonProject: "",
    team: "",
    tecnology: "HTML, CSS, Javascript",
    image: ["display1.png", "display2.png", "display3.png"],
    desc: "Sebuah website yang menyediakan layanan rekomendasi hp berdasarkan kriteria yang dimasuka pengguna.",
    linkRep: "https://github.com/dimaswidysap/rekomendasihp",
    linkDemo: "https://dimaswidysap.github.io/rekomendasihp/",
  },
  {
    id: "PJ002",
    year: "2026",
    title: "Vedeo TikTok Downloader",
    page: "/front-end/Vidsave",
    reasonProject: "Fetch API",
    team: "Widy",
    tecnology: "HTML, CSS, Javascript",
    image: [
      "vid-tiktok-downloader.png",
      "vid-tiktok-downloader2.png",
      "vid-tiktok-downloader3.png",
    ],
    desc: "Sebuah platform berbasis web yang memungkinkan pengguna mengunduh video TikTok tanpa watermark. Project ini merupakan implementasi praktis dari asynchronous JavaScript melalui pemanfaatan Fetch API untuk integrasi data secara real-time.",
    linkRep: "https://github.com/dimaswidysap/rekomendasihp",
    linkDemo: "https://dimaswidysap.github.io/vid-tiktok-downloader/",
  },

  {
    id: "PJ003",
    year: "2026",
    title: "WEB TodoList",
    page: "/front-end/Todolist",
    reasonProject: "Local Storage",
    team: "Widy",
    tecnology: "HTML, CSS, Javascript",
    image: ["todolist.png", "todolist2.png"],
    desc: "Sebuah website yang digunakan untuk mencatat semua aktivitas yang bertujuan untuk membuat lebih produktif",
    linkRep: "https://github.com/dimaswidysap/todolist",
    linkDemo: "https://dimaswidysap.github.io/todolist/",
  },
];
